server:
  port: 8081
  servlet:
    context-path: /luckeymoney

limit:
  minMoney: 1
  maxMoney: 10
  des: 最少${limit.minMoney}元,最多${limit.maxMoney}元

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luckymoney?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



